### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [Seeed-Studio/Grove_BME280#1]
When the Wire.requestFrom() returns, the I2C transaction has completely finished and the received data is in the receive buffer in the Wire library. There is no need to wait for something.

When there was a I2C bus error or I2C collision, the Wire.requestFrom() will probably return with no data. In that case, the while-loop will halt the sketch.

**Comment by KillingJacky** [comment]
Hi @Koepel , thanks for your percipience. If you like, could you please commit your patch for this driver with a pull-request? That prevents us reinvent the wheel and would be pretty appreciated.
