### ISSUE TITLE
Can't compile.

### ISSUE THREAD

**Issue by almog6k** [Seeed-Studio/Grove_BME280#2]
I am trying to use the example from this library and it fails to compile on both machines (Raspberry Pi and Windows 10.) 

`Arduino: 1.8.7 (Linux), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

/home/pi/Arduino/libraries/Grove_BME280-master/Seeed_BME280.cpp: In member function 'uint32_t BME280::BME280Read24(uint8_t)':
/home/pi/Arduino/libraries/Grove_BME280-master/Seeed_BME280.cpp:225:1: error: a function-definition is not allowed here before '{' token
 {
 ^
/home/pi/Arduino/libraries/Grove_BME280-master/Seeed_BME280.cpp:230:1: error: expected '}' at end of input
 }
 ^
exit status 1
`

**Comment by lanselambor** [comment]
@almog6k thank you pulling this issue, have fixed it.
