### ISSUE TITLE
Current name makes library difficult to auto-install.

### ISSUE THREAD

**Issue by flatsiedatsie** [Seeed-Studio/Grove_BME280#4]
Currently entering the #include name into the arduino search box does not help find the right library to download.

This is getting more important, as Arduino has a CLI now, which makes automatically downloading libraries a possibility.

- An option would be to rename "Seeed_BME280.h" to "Grove_BME280.h".
- Another option would be to change the name of the library as it appears in Arduino so that the name 'seeed' is part of it. That will help it be found.

**Comment by per1234** [comment]
Which version of the Arduino IDE are you using? From Arduino IDE 1.8.6 and onward, the `includes` field of library.properties is included in the Library Manager search query (https://github.com/arduino/Arduino/commit/60021c1e6394e20b33c58a587141eb86c11db5c9). This library does define the `includes` field:
https://github.com/Seeed-Studio/Grove_BME280/blob/1ff1fd1e9e5a1a9892d3f4b0d436b83bb10e7cad/library.properties#L10
When using a modern IDE version, if you search the Library Manager for "Seeed_BME280" or "Seeed_BME280.h", this library is the only search result.

**Comment by flatsiedatsie** [comment]
Interesting. I have the Arduino !DE 1.8.5, and there it doesn't work. I'll see if there's an update.
More importantly though, for my current case: it doesn't work in the Arduino CLI:

```
pi@gateway:~/uploader $ ./arduino-cli lib search "seeed bme280"
No library found matching `seeed bme280` search query
pi@gateway:~/uploader $ ./arduino-cli lib search "seeed_bme280"
No library found matching `seeed_bme280` search query
pi@gateway:~/uploader $ ./arduino-cli lib search Seeed_BME280.h
No library found matching `seeed_bme280.h` search query
```
Although this also doesn't work. Hmmm.
```
pi@gateway:~/uploader $ ./arduino-cli lib search "grove bme280"
No library found matching `grove bme280` search query
```
Searching for "grove bme280" did work in the Arduino 1.8.5 IDE.

Perhaps the Arduino CLI doesn't support all libraries yet.

**Comment by flatsiedatsie** [comment]
You're right, searching for "seeed BME280" does work in the latest version of the Arduino IDE.
So the Arduino CLI must use a different system. Perhaps this is because it is still in alpha.
