### ISSUE TITLE
calibrating pressure

### ISSUE THREAD

**Issue by corndog312** [Seeed-Studio/Grove_BME280#5]
I have seen other libraries that allow pressure data to be calibrated. for example, divide the pressure by 0.84.  I'm a bit of a noob and don't know where I would edit this information.
thanks!

**Comment by lanselambor** [comment]
@corndog312 The calibration data is a read-only factory setting, so I think you are talking about how to manually add a coefficient number to the original value. If that's right, you can just multiply the coefficient you need with the sense value.
